version: '3.3'
services:
  insurance-service:
    container_name: preapprove-process-module
    image: preapprove-process-module
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: "host"
    environment:
      CONSUL_DATA: "prod"
      INS_LOG_DIR: "/opt/logs"
    command: [ "java", "-jar", "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005", "preapprove-process-module.jar" ]
    volumes:
      - ./logs:/opt/logs
volumes:
  database-data:
    driver: local
  logs:
    driver: local
  camunda-data:
    driver: local